Updated multi-runner.yml

diff --git a/.github/workflows/multi-runner.yml b/.github/workflows/multi-runner.yml
--- a/.github/workflows/multi-runner.yml
+++ b/.github/workflows/multi-runner.yml
@@ -3,6 +3,7 @@ on:
   push:
     branches:
       - main
+
 jobs:
   build:
     runs-on: self-hosted
@@ -10,51 +11,52 @@ jobs:
       matrix:
         runner: [self-hosted, php-runner]
     steps:   
-      - name: Setup PHP        
+      - name: Checkout code        
         uses: actions/checkout@v2
+
       - name: Use PHP 8.2.x
         uses: shivammathur/setup-php@v2
         with:
           php-version: 8.2.x
+
       - name: Check if composer.json exists
         id: check_files
-        uses: andstor/file-existence-action@v2
-        with:
-          files: 'composer.json'
+        run: test -f composer.json && echo "Found" || echo "Not found"
+
       - name: Get Composer Cache Directory
-        id: composer-cache
-        if: steps.check_files.outputs.files_exists == 'true'
+        if: steps.check_files.outputs.files_exists == 'Found'
         run: |
-          echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
+          echo "dir=$(composer config cache-files-dir)" >> $GITHUB_ENV
+
       - name: Set up dependency caching for faster installs
-        uses: actions/cache@v3
-        if: steps.check_files.outputs.files_exists == 'true'
+        if: steps.check_files.outputs.files_exists == 'Found'
+        uses: actions/cache@v2
         with:
-          path: ${{ steps.composer-cache.outputs.dir }}
+          path: ${{ env.dir }}
           key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
           restore-keys: |
             ${{ runner.os }}-composer-
+
       - name: Run composer install if composer.json exists
-        if: steps.check_files.outputs.files_exists == 'true'
+        if: steps.check_files.outputs.files_exists == 'Found'
         run: composer validate --no-check-publish && composer install --prefer-dist --no-progress
+
       - name: Update Composer
         run: composer self-update
+
       - name: Install Dependencies
         run: composer update
-        
+
       - name: Install zip
         run: |
           sudo apt-get update
           sudo apt-get install -y zip
+
       - name: Zip artifact for deployment
-        run: zip release.zip ./* -r
+        run: zip -r release.zip *
+
       - name: Upload artifact for deployment job
-        uses: actions/upload-artifact@v3
+        uses: actions/upload-artifact@v2
         with:
-         name: php-app
-         path: release.zip
-
-
-	 
-
-	 
+          name: php-app
+          path: release.zip
